---
shell_path: /usr/local/bin/zsh

homebrew_taps:
  - homebrew/cask-fonts
  - homebrew/cask-versions

homebrew_apps: #This are `casks` in homebrew speak
# Install firefox
  - firefox

# OSX Install Cascadia Code Fonts
  - font-cascadia-code
  - font-cascadia-code-pl
  - font-cascadia-code-mono
  - font-cascadia-code-mono-pl

# Terminal emulator as alternative to Apple's Terminal app
  - iterm2

# Move and resize windows using keyboard shortcuts or snap areas
  - rectangle

# Install VSCode
  - visual-studio-code

# Install flameshot, screenshot tool similar to `snipping tool` from Windows
  - flameshot

# Install alt-tab for a Windows-like alt-tab experience
  - alt-tab

# Install Obisidian MD for note-taking
  - obsidian

# Install UTM for virtualization on Apple Silicon
  - utm
  
# Install unnaturalscrollwheels which allows scrolling to be inverted on mice
  - unnaturalscrollwheels

# Install vlc
  - vlc

# Install appcleaner
  - appcleaner

# Install Drivers for DisplayLink docks, adapters and monitors
  - displaylink

# Install Microsoft RDP Client 🤢🤮
  - microsoft-remote-desktop

# Install monitorcontrol to use the native DDC/CI of external monitors to control their brightness and contrast and volume through the menu bar rather than the physical monitor controls
  - monitorcontrol

# Install wireshark
  - wireshark

# Install Signal
  - signal
  
homebrew_packages:
  - ansible
  - nmap
  - htop
  - zsh-completions
  - docker #🐳
  - tldr



# MAS (Mac App Store) applications
# Commented out since MAS are not currently being used, but kept
# mas_apps:
#  - { name: 1Blocker, id: 1107421413 }
#  - { name: 1Password for Safari, id: 1569813296 }
#  - { name: Amphetamine, id: 937984704 }
#  - { name: JSONPeep, id: 1458969831 }
#  - { name: Mela, id: 1568924476 }
#  - { name: Numbers, id: 409203825 }
#  - { name: Pages, id: 409201541 }
#  - { name: Patterns, id: 429449079 }
#  - { name: Pins, id: 1547106997 }
#  - { name: Pixelmator Pro, id: 1289583905 }
#  - { name: Refined GitHub, id: 1519867270 }
#  - { name: StopTheMadness, id: 1376402589 }
#  - { name: Things, id: 904280696 }
#  - { name: uBlacklist for Safari, id: 1547912640 }
