---

#Adding to try and troubleshooting why Brew casks is failing
#- name: Debug homebrew_taps
#  debug:
#    var: homebrew_taps
#- name: Ensure taps
#  homebrew_tap:
#    name: "{{ item.name|default(item) }}"
#    state: "{{ item.state|default('present') }}"
#  loop: "{{ homebrew_taps }}"
#  when: homebrew_taps|default([])|count > 0

#Adding to try and troubleshooting why Brew casks is failing
#- name: Update Homebrew
#  homebrew:
#    name: "{{ item.name|default(item) }}"
#    state: latest
#  loop:
#    - ansible


- name: Ensure taps
  homebrew_tap:
    name: "{{ item.name|default(item) }}"
    state: "{{ item.state|default('present') }}"
  loop: "{{ homebrew_taps }}"
  when: homebrew_taps|default([])|count > 0 and ('homebrew/cask' not in item|default('')) #This was added to skip the `homebrew/casks` error

- name: Ensure apps
  homebrew_cask:
    name: "{{ item.name|default(item) }}"
    state: "{{ item.state|default('present') }}"
    install_options: "{{ item.install_options | default(omit) }}"
    accept_external_apps: yes
  loop: "{{ homebrew_apps }}"
  when: homebrew_apps|default([])|count > 0

- name: Ensure packages
  homebrew:
    name: "{{ item.name|default(item) }}"
    state: "{{ item.state|default('present') }}"
    install_options: "{{ item.install_options | default(omit) }}"
  loop: "{{ homebrew_packages }}"
  when: homebrew_packages|default([])|count > 0
